name: Dart Unit Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      
      - name: Run Logic Check
        run: |
          RESULT=$(dart main.dart | grep "Total Price: 115.0")
          if [ -z "$RESULT" ]; then
            echo "Test Failed"
            exit 1
          else
            echo "Test Passed"
          fi
